### ISSUE TITLE
Sort out islandora linking between researchers and publications

### ISSUE THREAD

**Issue by ihardy** [WRLC/orcid_task_service#20]
Right now displayform in MODs references the u1 identifier in MADs. 

If there is an existing work identified by an email in u1, it's relationship will be lost if we update the u1 to orcid.

Can we work around this by having a u1 and a u2, or perhaps having two u1s?

This will be a change to the islandora config.

**Comment by krebeck** [comment]
Looks like the u2 identifier is reserved for assigning a department to a person entity.  See code snippet below.  But in same code, I'm not sure how two u1s would work.  Looks like it's assigning whatever is in u1 position as the username.  So it's probably writing the first u1 as the username and then immediately overwriting that with the second u1 which is why we are seeing the behavior of picking up the second u1.

    $username = $xml->xpath('//mods:identifier[@type="u1"]');
    if ($username) {
      $this->username = $username;
    }
    $department = $xml->xpath('//mods:identifier[@type="u2"]');
    if ($department) {
      $this->department = $department;
    }
  }

**Comment by ihardy** [comment]
We decided to use the existing linking field (name.displayForm in mods links to identifier.u1 in mads).
