### ISSUE TITLE
xslt to create mods

### ISSUE THREAD

**Issue by ihardy** [WRLC/orcid_task_service#28]
Use XSLT instead of spaghetti code to map orcid to MODS.

**Comment by ihardy** [comment]
bug fixes from Don:

1. Can you get the author(s) from the citation? It doesn't currently show co-authors and, in the APA display at least the name is coming out with an extraneous ',' after it instead of being in "Last, first initial" format. See https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1680

2. For books, the ISBN link (which is relationship SELF) is not displayed. And the Related Title is the publisher? See https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1680

3. You don't have the last citation that I put in ORCID that has a link (<work:url>) to the actual document. See https://pub.orcid.org/v2.0/0000-0002-3948-8942/work/41386462 . I assume that's because you were using an ORCID works URL from before that...I'll blow the existing ones away and re-test and make sure that comes up and see how the link is displayed. But I won't do that until tomorrow probably -- and also work on integrating this with the Create-on-demand page this weekend.

**Comment by krebeck** [comment]
I have added the ISBN link and Location link (work:url) to the metadata display.  The way SOLR indexing works (at least in Islandora), those new fields weren't actually available for me to select until they were used at least once by an object.  Since there are so few objects in the sandbox, there aren't many SOLR fields for me to choose. I actually needed those objects to have those fields before I could actually put them in the metadata display. 

However, I'm still seeing a few issues:

1.  This one is tricky.  The citation is picking up whatever we have in the MODS author field.  We're not adding co-authors to the ORCID XML so no real way to get them into the MODS.  I think the real issue is that ORCID is not enforcing any structure to the "author" field.  You couId enter your name as Don Gourley, but could just as easily put Don P. Gourley or D. Philip Gourley.  I could probably tweak the XSLT to break Don Gourley in something like the below, but it will only work if the incoming data looks like that every time.  I'm not sure we can write an XSLT that assumes every possible combo.  In order to do last name first, the MODS needs to be like this:

<name type="personal">
<role>
<roleTerm authority="marcrelator" type="text">author</roleTerm>
</role>
<namePart type="given">Stefan</namePart>
<namePart type="family">Kramer</namePart>
</name>

2. Self link is now displaying.  Not sure how to fix publisher.  Could you send me the ORCID link (or at least the work number) for this one:  https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1681

3.  Same SOLR indexing issue as before.  I now have metadata displays for the <location> field.

**Comment by krebeck** [comment]
Hah.  It converted my MODS in the above response to text.  For an example of what incoming MODS would have to look like, go here:

https://auislandora-dev.wrlc.org/islandora/object/ir%3A7/datastream/MODS/view

The other option here is to tweak the CSL, but I really don't think I can figure that out in short order.

**Comment by krebeck** [comment]
I'm noticing at least one other potential issue.  The item link on this one is broken: https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1681 because the ISBN in the ORCID has spaces.  So the incoming ORCID is passing a broken link to OCLC.  If we think this will be a common occurrence, we might need to strip white space in the XSLT.

I also noticed that it might be helpful to have the publication type (conference paper, journal article, etc) in the metadata display.  So I've added that one.

**Comment by krebeck** [comment]
One more issue:

The citation objects that we are creating do not have a parent collection.  As a result, they are not discoverable via browse.  They only really exist when linked to author or as search results.  They should really have a parent collection somewhere.  I've created this collection for this purpose:
https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1684

I recommend giving them a RELS-EXT relationship to this collection as shown below (minus quotes):
"<fedora:isMemberOfCollection rdf:resource="info:fedora/auislandora:1684"></fedora:isMemberOfCollection>"

**Comment by ihardy** [comment]
I'll add the RELS-EXT you're describing to this pull request. FYI, this branch is live on ops.wrlc.org, I can pull the latest if there are commits that need testing.

Also adding a bugfix, right now I'm giving back the wrong response code if the status is updated or pass (500) put in a fix to give 201.

**Comment by krebeck** [comment]
If this goes into production, the XSL should really try to grab the DOI if not done already.
